### ISSUE TITLE
SSL Support is not present

### ISSUE THREAD

**Issue by JFGHT** [IkeC/evo-league#8]
This is the error i got while trying to run the service.sh

"assert sslEnabled, "SSL support is not present"
exceptions.AssertionError: SSL support is not present

Failed to load application: SSL support is not present"

My server does have SSL correctly installed... so whats going on here?

**Comment by IkeC** [comment]
Using SSL in Twisted requires that you have pyOpenSSL installed.

http://twistedmatrix.com/documents/11.0.0/core/howto/ssl.html

In *pip.requirements*: 
```pyOpenSSL==0.13
is defined, which should be used when you compile your virtualenv environment with *make install*. Check the output if pyOpenSSL is linked correctly.

Actually, if you don't need the server admin web-service, you could probably remove or comment these lines in */Sixserver/etc/sixserver.tac* 
```
class ServerContextFactory:
    def getContext(self):
        from OpenSSL import SSL
        ctx = SSL.Context(SSL.SSLv23_METHOD)
        ctx.use_privatekey_file(
            '%s/serverkey.pem' % adminConfig.KeysDirectory)
        ctx.use_certificate_file(
            '%s/servercert.pem' % adminConfig.KeysDirectory)
        return ctx

adminConfig = YamlConfig('/opt/sixserver/etc/conf/admin6.yaml')

# server admin web-service (HTTPS, authentication)
adminRoot = admin.AdminRootResource(adminConfig, config)
adminRoot.putChild('', adminRoot)
adminRoot.putChild('home', adminRoot)
adminRoot.putChild('xsl', admin.XslResource(adminConfig))
adminRoot.putChild('log', admin.LogResource(adminConfig, config))
adminRoot.putChild('biglog', admin.LogResource(adminConfig, config))
usersResource = admin.UsersResource(adminConfig, config)
adminRoot.putChild('users', usersResource)
usersResource.putChild(
    'online', admin.UsersOnlineResource(adminConfig, config))
adminRoot.putChild('stats', admin.StatsResource(adminConfig, config))
adminRoot.putChild('profiles', admin.ProfilesResource(adminConfig, config))
adminRoot.putChild(
    'userlock', admin.UserLockResource(adminConfig, config))
adminRoot.putChild(
    'userkill', admin.UserKillResource(adminConfig, config))
adminRoot.putChild('debug', admin.DebugResource(adminConfig, config))
adminRoot.putChild('maxusers', admin.MaxUsersResource(adminConfig, config))
adminRoot.putChild('settings', admin.StoreSettingsResource(adminConfig, config))
adminRoot.putChild('roster', admin.RosterResource(adminConfig, config))
adminRoot.putChild('banned', admin.BannedResource(adminConfig, config))
adminRoot.putChild('ban-add', admin.BanAddResource(adminConfig, config))
adminRoot.putChild(
    'ban-remove', admin.BanRemoveResource(adminConfig, config))
adminRoot.putChild('server-ip', admin.ServerIpResource(adminConfig, config))
adminRoot.putChild('ps', admin.ProcessInfoResource(adminConfig, config))
adminServer = Site(adminRoot)
reactor.listenSSL(adminConfig.AdminPort, adminServer, ServerContextFactory(),
    interface=config.interface)
```

**Comment by JFGHT** [comment]
Thanks for your fast answer.

The pip.requirements downloaded from here: https://sites.google.com/site/fiveservercom/home is outdated (it's the one I had) even tho the sixserver version is supposed to be the updated one (4.9) when here it's 4.8.

After updating it myself and running again make install, the service runs perfectly.

So at this point it makes me thing, are there any other outdated files from the other version?

**Comment by IkeC** [comment]
Everything you need should be in this reopsitory here, you should not need anything from https://sites.google.com/site/fiveservercom/home. If that's not correct, or the documentation is misleading, please help improving it.

**Comment by JFGHT** [comment]
Well, I've fully replaced the files from my server (which were the ones dled from the link I wrote above) with the ones I've dled from here and it's a complete chaos.

First of all, paths stored in service.sh file are completely useless since they're static, not relative paths.

And second, after I fixed the paths and run the .sh it shows:

"File "/root/fsenv/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 34, in __init__
    assert os.path.isdir(self.directory)
exceptions.AssertionError:

Failed to load application:"

So, I'm going to keep trying with this version following your advice but it doesn't seem like it's the final one :S

**Comment by IkeC** [comment]
Replacing an existing fiveserver with this doesn't work. The Sixserver here only works properly with the website part (eg. the user information is stored in and read from a different table than in fiveserver).

Also, you may encounter problems using Python 2.7 instead of 2.6, at least I didn't get it to work properly with it the last time I tried.

**Comment by AkatsukiTeam** [comment]
I setup website with dbinit.sql , how can i use this sql with sixserver on this link >>>https://sites.google.com/site/fiveservercom/win32-howto

**Comment by akatsuki244** [comment]
./service.sh: 25: ./service.sh: FSENV}/bin/twistd: not found

**Comment by wladymeer** [comment]
Getting same error - pyOpenSSL==0.13 is fixed

I've managed to do make install, however when I triger ./service.sh sixserver start (or run) I get 

> Traceback (most recent call last):
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 631, in run
    runApp(config)
  File "/root/fsenv/lib/python2.6/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 374, in run
    self.application = self.createOrGetApplication()
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 439, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 450, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/service.py", line 400, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/root/fsenv/lib/python2.6/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "./etc/sixserver.tac", line 111, in <module>
    interface=config.interface)
  File "/root/fsenv/lib/python2.6/site-packages/twisted/internet/posixbase.py", line 442, in listenSSL
    assert sslEnabled, "SSL support is not present"
exceptions.AssertionError: SSL support is not present

Failed to load application: SSL support is not present

**Comment by IkeC** [comment]
Try removing the server admin web-service as I suggested in https://github.com/IkeC/evo-league/issues/8#issuecomment-110363572.

**Comment by wladymeer** [comment]
It detects adminConfig missing

`File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 631, in run
    runApp(config)
  File "/root/fsenv/lib/python2.6/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 374, in run
    self.application = self.createOrGetApplication()
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 439, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/app.py", line 450, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/root/fsenv/lib/python2.6/site-packages/twisted/application/service.py", line 400, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/root/fsenv/lib/python2.6/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "./etc/sixserver.tac", line 72, in <module>
    statsRoot = admin.StatsRootResource(adminConfig, config, False)
exceptions.NameError: name 'adminConfig' is not defined

Failed to load application: name 'adminConfig' is not defined`

**Comment by wladymeer** [comment]
Actually I've found a solution....

It's all about organizing Linux install commands before setting fiveserver up. So what I did is make a fresh re-install, update first, set everything up including mySQL (but not databases) and then it worked out with no hustle... This time I wrote down whole log, so I guess I won't have trouble next time :)

**Comment by IkeC** [comment]
Nice to hear you got it working!
